moje_blog:
    resource: "@MojeBlogBundle/Resources/config/routing.yml"
    prefix:   /

moje_demo123:
    resource: "@MojeDemo123Bundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation