index:
    path:     /{page}
    defaults: { _controller: MojeBlogBundle:Blog:index, page: 1 }
    requirements:
        page:  \d+
    
add_article:
    path:     /add_article
    defaults: { _controller: MojeBlogBundle:Blog:addArticle }
    
show_article:
    path:     /article/{idArticle}
    defaults: { _controller: MojeBlogBundle:Blog:article, idArticle: 1 }
    requirements:
        page:  \d+    