moje_blog_homepage:
    path:     /hello/{name}
    defaults: { _controller: MojeBlogBundle:Default:index }

create_new_product:
    path:     /new_prod
    defaults: { _controller: MojeBlogBundle:Default:create }
    
show_product:
    path:     /show/{id}
    defaults: { _controller: MojeBlogBundle:Default:show }
    
form:
    path:     /form
    defaults: { _controller: MojeBlogBundle:Default:form }
    
form_and_doctrine:
    path:     /form_and_doctrine
    defaults: { _controller: MojeBlogBundle:Default:formAndDoctrine }
    
new_wpis:
    path:     /new_wpis
    defaults: { _controller: MojeBlogBundle:Default:newWpis }
    
show_wpis:
    path:     /show_wpis
    defaults: { _controller: MojeBlogBundle:Default:showWpis }
    
index_show_blog:
    path:     /abc/{page}
    defaults: { _controller: MojeBlogBundle:Default:index, page = 1 }
    methods:  [GET]
    
index_add:
    path:     /abc/{page}
    defaults: { _controller: MojeBlogBundle:Default:indexAdd, page = 1 }
    methods:  [POST]    
    
index_show_one_wpis:
    path:     /abc/{nazwa_wpisu}
    defaults: { _controller: MojeBlogBundle:Default:indexAdd  }
    
index:
    path:     /{page}
    defaults: { _controller: MojeBlogBundle:Blog:index, page: 1 }
    requirements:
        page:  \d+
    
add_article:
    path:     /add_article
    defaults: { _controller: MojeBlogBundle:Blog:addArticle }
    
show_article:
    path:     /article/{idArticle}
    defaults: { _controller: MojeBlogBundle:Blog:article, idArticle: 1 }
    requirements:
        page:  \d+    